### ISSUE TITLE
能把每个文件做一个简要的说明吗？

### ISSUE THREAD

**Issue by lukemin** [Asutorufa/ACL#2]
没看懂你的说明！

**Comment by Asutorufa** [comment]
my.acl去广告条目比较多，有误杀的可能，
my-light.acl有国内的一些去广告还有谷歌和雅虎的一些去广告，my-none.acl没有去广告，这三个文件都是如果没有匹配到文件内直连的条目默认走代理，还有一个默认直连的readme有写，外部还有一些sh脚本就是用来更新的。

**Comment by lukemin** [comment]
建议你能像https://github.com/ACL4SSR/ACL4SSR一样做个表格说明 :)

**Comment by Asutorufa** [comment]
好的 有时间更新一下

**Comment by Asutorufa** [comment]
改好了 你可以看一下效果
